<?php
require_once "includes/tripal_cmap_loader.fields.inc";


function tripal_cmap_loader_bundle_instances_info_alter(&$instances, $bundle, $term) {

  if (isset($bundle->data_table) AND ($bundle->data_table == 'featuremap')) {

    dpm($instances['local__cmap_viewer']);
    $instances['local__cmap_viewer']['label'] = 'cMap flat file';
    $instances['local__cmap_viewer']['required'] = FALSE;
    $instances['local__cmap_viewer']['widget']['type'] = 'text_textfield';
    $instances['local__cmap_viewer']['settings']['text_processing'] = '0';
    $instances['local__cmap_viewer']['settings']['max_length'] = 200;

    $instances['local__cmap_viewer']['weight'] = 0;
  }
}